### ISSUE TITLE
Add Discord theme

### ISSUE THREAD

**Issue by gustavolbs** [getomni/omni#40]
## New theme idea

I had made a customization on discord using the [Better Discord Library](http://betterdiscordlibrary.com/) with Omni Theme, It'll be good if you add it to the comunity.

**Application:** Discord
**Application URL** https://discord.com/
**Library:** https://betterdiscordlibrary.com/

## Existing Theme

```css
:root {
  /* Omni Colors */
  --omni-background: #191622 !important;
  --omni-current-line: #41414D !important;
  --omni-selection: #41414D !important;
  --omni-foreground: #E1E1E6 !important;
  --omni-comment: #5A4B81 !important;
  --omni-cyan: #988bc7 !important;
  --omni-green: #67e480 !important;
  --omni-orange: #E89E64 !important;
  --omni-pink: #FF79C6 !important;
  --omni-purple: #78D1E1 !important;
  --omni-red: #E96379 !important;
  --omni-yellow: #e7de79 !important;

  /* Discord Root Colors */
  --background-primary: var(--omni-background) !important;
  --background-secondary: var(--omni-background) !important;
  --background-secondary-alt: var(--omni-background) !important;
  --background-tertiary: var(--omni-background) !important;
  --background-accent: var(--omni-current-line) !important;
  --background-floating: var(--omni-background) !important;
  --background-message-hover: var(--omni-selection) !important;
  --activity-card-background: var(--omni-background) !important;
  --interactive-normal: var(--omni-foreground) !important;
  --channeltextarea-background: var(--omni-selection) !important;
  --rs-online-color: var(--omni-green) !important;
  --rs-idle-color: var(--omni-orange) !important;
  --rs-dnd-color: var(--omni-red) !important;
  --rs-offline-color: var(--omni-selection) !important;
  --rs-streaming-color: var(--omni-purple) !important;
  --rs-invisible-color: var(--omni-comment) !important;
  --interactive-muted: var(--omni-comment) !important;
}

.da-acronym {
  --background-primary: var(--omni-selection) !important;
}

.da-repliedMessage {
    --background-accent: var(--omni-selection) !important;
}

.container-1D34oG.da-container {
  background-color: var(--omni-background) !important;
}

.wrapper-1BJsBx.selected-bZ3Lue .childWrapper-anI2G9, .wrapper-1BJsBx:hover .childWrapper-anI2G9 {
  background-color: var(--omni-selection) !important
}

.theme-dark .scrollerThemed-2oenus.themedWithTrack-q8E3vB .scroller-2FKFPG::-webkit-scrollbar-track-piece {
  background-color: var(--omni-selection) !important;
  border: 4px solid var(--omni-background) !important;
  border-radius: 8px !important;
}



/* Syntax Highlighing in Code Blocks*/
code {
  /* background-color: #282a36 !important; */
  background-color: var(--omni-current-line) !important;
  color: var(--omni-foreground) !important
}
span.hljs-built_in {
  color: var(--omni-purple) !important;
}
span.hljs-keyword {
  color: var(--omni-pink) !important;
}
span.hljs-title {
  color: var(--omni-cyan) !important;
}
span.hljs-attr {
  color: var(--omni-foreground) !important;
}
span.hljs-string {
  color: var(--omni-yellow) !important;
}
span.hljs-number {
  color: var(--omni-purple) !important;
}
span.hljs-symbol {
  color: var(--omni-orange) !important;
}
span.hljs-meta {
  color: var(--omni-foreground) !important;
}
span.hljs-meta-keyword {
  color: var(--omni-pink) !important;
}
span.hljs-meta-string {
  color: var(--omni-orange) !important;
}
```
